apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-wordpress
  labels:
    app: {{ .Release.Name}}-wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: {{ .Values.container.image }}
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.wordpressDbHost }}
        - name: WORDPRESS_DB_PASSWORD
          value: {{ .Values.wordpressDbPassword }}
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim